/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  connection_id: string;
  contract_addr: string;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  mint_nft: {
    token_id: string;
    [k: string]: unknown;
  };
} | {
  register_transfer_nft_query: {
    connection_id: string;
    contract_address: string;
    min_height: number;
    recipient: string;
    sender: string;
    token_id: string;
    update_period: number;
    [k: string]: unknown;
  };
} | {
  remove_interchain_query: {
    query_id: number;
    [k: string]: unknown;
  };
} | {
  unlock_nft: {
    destination: string;
    token_id: string;
    [k: string]: unknown;
  };
};
export type QueryMsg = {
  transfer_nft: {
    query_id: number;
    [k: string]: unknown;
  };
} | {
  get_registered_query: {
    query_id: number;
    [k: string]: unknown;
  };
};
export type Uint128 = string;
export type Binary = string;
export type QueryType = "kv" | "tx";
export interface QueryRegisteredQueryResponse {
  registered_query: RegisteredQuery;
  [k: string]: unknown;
}
export interface RegisteredQuery {
  connection_id: string;
  deposit?: Coin[];
  id: number;
  keys: KVKey[];
  last_submitted_result_local_height?: number;
  last_submitted_result_remote_height?: Height;
  owner: string;
  query_type: QueryType;
  registered_at_height?: number;
  submit_timeout?: number;
  transactions_filter: string;
  update_period: number;
  [k: string]: unknown;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface KVKey {
  key: Binary;
  path: string;
  [k: string]: unknown;
}
export interface Height {
  revision_height?: number;
  revision_number?: number;
  [k: string]: unknown;
}
export interface TransferNftResponse {
  contract_address: string;
  sender: string;
  token_id: string;
  [k: string]: unknown;
}