/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.26.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./BadBridge.types";
import * as _1 from "./BadBridge.client";
import * as _2 from "./BadBridge.react-query";
export namespace contracts {
  export const BadBridge = { ..._0,
    ..._1,
    ..._2
  };
}