import Head from 'next/head';
import {
  Box,
  Divider,
  Grid,
  Heading,
  Text,
  Stack,
  Container,
  Link,
  Button,
  Flex,
  Icon,
  useColorMode,

  Image,
} from '@chakra-ui/react';
import { BsFillMoonStarsFill, BsFillSunFill } from 'react-icons/bs';
import { dependencies, products } from '../config';
import NextLink from 'next/link';

import {
  Product,
  Dependency,
  WalletSection,
  handleChangeColorModeValue,
  FromStargaze,
} from '../components';
import { ChainContractProvider } from 'components/chain-provider';
import { ArrowForwardIcon } from 'components/wallet-ui';

const library = {
  title: 'StargazeJS',
  text: 'Typescript libraries for the Stargaze ecosystem',
  href: 'https://github.com/cosmology-tech/stargazejs',
};

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <Container maxW="5xl" py={10}>
      <Head>
        <title>Bad Bridge</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex justifyContent="end" mb={4}>
        <Button variant="outline" px={0} onClick={toggleColorMode}>
          <Icon
            as={colorMode === 'light' ? BsFillMoonStarsFill : BsFillSunFill}
          />
        </Button>
      </Flex>
      <Box textAlign="center">
        <NextLink href="/">
          <Heading
            as="h1"
            fontSize={{ base: '3xl', md: '5xl' }}
            fontWeight="extrabold"
            mb={3}
          >
            <Image
              src={ colorMode === 'light' ? '/bad bridge text.png'  : '/bad bridge white text.png'}
              alt="Bad Bridge"
            />
            <Text fontSize={{ base: 'xxx-large', md: 'xxx-large' }} textAlign="center" mb={6} mt={12}>
            don’t tell us where we can or can’t be
            </Text>
          </Heading>
        </NextLink>
      </Box>

      <WalletSection />

      <FromStargaze />


      <Flex justifyContent="center" mb={4}>
        <NextLink href="from-neutron">
          <Button  rightIcon={<ArrowForwardIcon />}
          border="hidden"
          background="transparent"
          fontSize={{ base: 'xx-large', md: 'xx-large' }}
          color={colorMode === 'light' ? 'black' : 'white'}
          fontWeight={500}
          >
            Be Good
          </Button>
        </NextLink>
      </Flex>


    </Container>
  );
}
